// Generates DOCX and PDF documents from a structured template
// by substituting placeholders. The original template content,
// numbering, headings, spacing and signature blocks are preserved.
// No AI rewriting occurs anywhere in this module.

import { applyPlaceholders } from "./placeholders";

// ---- DOCX generation (uses `docx` library — only loaded client-side) ----

export async function generateDocx({ template, values, meta = {} }) {
  const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, Footer, Header, PageNumber } =
    await import("docx");

  const headerPara = new Paragraph({
    alignment: AlignmentType.RIGHT,
    children: [
      new TextRun({
        text: `${values.CompanyName || "Company"} · ${template.name} · ${template.version}`,
        size: 16,
        color: "6b7280",
      }),
    ],
  });

  const footerPara = new Paragraph({
    alignment: AlignmentType.CENTER,
    children: [
      new TextRun({ text: "Page ", size: 16, color: "9ca3af" }),
      new TextRun({ children: [PageNumber.CURRENT], size: 16, color: "9ca3af" }),
      new TextRun({ text: " of ", size: 16, color: "9ca3af" }),
      new TextRun({ children: [PageNumber.TOTAL_PAGES], size: 16, color: "9ca3af" }),
      new TextRun({
        text: `   ·   Generated by NDAFlow ${meta.documentId ? "· " + meta.documentId : ""}`,
        size: 16,
        color: "9ca3af",
      }),
    ],
  });

  const children = [];

  for (const block of template.content) {
    if (block.type === "title") {
      children.push(
        new Paragraph({
          alignment: AlignmentType.CENTER,
          spacing: { before: 120, after: 240 },
          children: [
            new TextRun({
              text: applyPlaceholders(block.text, values),
              bold: true,
              size: 32,
            }),
          ],
        })
      );
    } else if (block.type === "subtitle") {
      children.push(
        new Paragraph({
          alignment: AlignmentType.CENTER,
          spacing: { after: 240 },
          children: [
            new TextRun({
              text: applyPlaceholders(block.text, values),
              italics: true,
              color: "475569",
              size: 22,
            }),
          ],
        })
      );
    } else if (block.type === "heading") {
      children.push(
        new Paragraph({
          heading: HeadingLevel.HEADING_2,
          spacing: { before: 240, after: 120 },
          children: [
            new TextRun({
              text: applyPlaceholders(block.text, values),
              bold: true,
              size: 24,
            }),
          ],
        })
      );
    } else if (block.type === "paragraph") {
      children.push(
        new Paragraph({
          spacing: { after: 160, line: 320 },
          alignment: AlignmentType.JUSTIFIED,
          children: [
            new TextRun({
              text: applyPlaceholders(block.text, values),
              size: 22,
            }),
          ],
        })
      );
    } else if (block.type === "spacer") {
      children.push(new Paragraph({ children: [new TextRun({ text: " " })] }));
    } else if (block.type === "signatureBlock") {
      children.push(
        new Paragraph({
          spacing: { before: 240, after: 120 },
          children: [
            new TextRun({
              text: "IN WITNESS WHEREOF, the Parties hereto have executed this Agreement as of the Effective Date.",
              size: 22,
            }),
          ],
        })
      );
      for (const p of block.parties) {
        children.push(
          new Paragraph({
            spacing: { before: 240 },
            children: [
              new TextRun({
                text: applyPlaceholders(p.party, values),
                bold: true,
                size: 22,
              }),
            ],
          })
        );
        children.push(
          new Paragraph({
            spacing: { before: 360 },
            children: [
              new TextRun({ text: "By: ____________________________________", size: 22 }),
            ],
          })
        );
        children.push(
          new Paragraph({
            children: [
              new TextRun({ text: `Name: ${applyPlaceholders(p.name, values)}`, size: 22 }),
            ],
          })
        );
        if (p.title) {
          children.push(
            new Paragraph({
              children: [
                new TextRun({ text: `Title: ${applyPlaceholders(p.title, values)}`, size: 22 }),
              ],
            })
          );
        }
        children.push(
          new Paragraph({
            children: [new TextRun({ text: "Date: __________________________", size: 22 })],
          })
        );
      }
    }
  }

  const doc = new Document({
    creator: "NDAFlow AI",
    title: `${template.name} — ${values.CounterpartyName || ""}`.trim(),
    description: `Generated from template ${template.id} ${template.version}`,
    styles: {
      default: {
        document: {
          run: { font: "Calibri", size: 22 },
        },
      },
    },
    sections: [
      {
        properties: {
          page: { margin: { top: 1080, bottom: 1080, left: 1080, right: 1080 } },
        },
        headers: { default: new Header({ children: [headerPara] }) },
        footers: { default: new Footer({ children: [footerPara] }) },
        children,
      },
    ],
  });

  const blob = await Packer.toBlob(doc);
  return blob;
}

// ---- PDF generation (jsPDF — client-side, demo grade) ----
// Visually mirrors the DOCX layout while preserving the original content.

export async function generatePdf({ template, values, meta = {} }) {
  const { jsPDF } = await import("jspdf");
  const doc = new jsPDF({ unit: "pt", format: "letter" });

  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();
  const margin = 56;
  const maxW = pageW - margin * 2;
  let y = margin;

  const drawHeader = () => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(120, 120, 130);
    doc.text(
      `${values.CompanyName || "Company"}  ·  ${template.name}  ·  ${template.version}`,
      pageW - margin,
      32,
      { align: "right" }
    );
    doc.setDrawColor(220);
    doc.line(margin, 40, pageW - margin, 40);
  };

  const drawFooter = (pageNum, totalPages) => {
    doc.setFont("helvetica", "normal");
    doc.setFontSize(8);
    doc.setTextColor(150);
    const text = `Page ${pageNum} of ${totalPages}    ·    Generated by NDAFlow${meta.documentId ? " · " + meta.documentId : ""}`;
    doc.text(text, pageW / 2, pageH - 24, { align: "center" });
  };

  const ensureSpace = (needed) => {
    if (y + needed > pageH - margin - 20) {
      doc.addPage();
      y = margin;
      drawHeader();
    }
  };

  drawHeader();

  for (const block of template.content) {
    if (block.type === "title") {
      ensureSpace(40);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(16);
      doc.setTextColor(15, 23, 42);
      doc.text(applyPlaceholders(block.text, values), pageW / 2, y, { align: "center" });
      y += 28;
    } else if (block.type === "subtitle") {
      ensureSpace(20);
      doc.setFont("helvetica", "italic");
      doc.setFontSize(11);
      doc.setTextColor(100);
      doc.text(applyPlaceholders(block.text, values), pageW / 2, y, { align: "center" });
      y += 22;
    } else if (block.type === "heading") {
      ensureSpace(28);
      doc.setFont("helvetica", "bold");
      doc.setFontSize(12);
      doc.setTextColor(15, 23, 42);
      doc.text(applyPlaceholders(block.text, values), margin, y);
      y += 18;
    } else if (block.type === "paragraph") {
      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      doc.setTextColor(30, 41, 59);
      const text = applyPlaceholders(block.text, values);
      const lines = doc.splitTextToSize(text, maxW);
      for (const line of lines) {
        ensureSpace(16);
        doc.text(line, margin, y);
        y += 14;
      }
      y += 6;
    } else if (block.type === "spacer") {
      y += 14;
    } else if (block.type === "signatureBlock") {
      ensureSpace(40);
      doc.setFont("helvetica", "normal");
      doc.setFontSize(11);
      doc.setTextColor(30, 41, 59);
      const intro = "IN WITNESS WHEREOF, the Parties hereto have executed this Agreement as of the Effective Date.";
      const lines = doc.splitTextToSize(intro, maxW);
      lines.forEach((l) => {
        ensureSpace(16);
        doc.text(l, margin, y);
        y += 14;
      });
      y += 10;

      for (const p of block.parties) {
        ensureSpace(80);
        doc.setFont("helvetica", "bold");
        doc.text(applyPlaceholders(p.party, values), margin, y);
        y += 22;
        doc.setFont("helvetica", "normal");
        doc.text("By: ____________________________________", margin, y);
        y += 16;
        doc.text(`Name: ${applyPlaceholders(p.name, values)}`, margin, y);
        y += 14;
        if (p.title) {
          doc.text(`Title: ${applyPlaceholders(p.title, values)}`, margin, y);
          y += 14;
        }
        doc.text("Date: __________________________", margin, y);
        y += 22;
      }
    }
  }

  // Page numbering footers
  const total = doc.internal.getNumberOfPages();
  for (let i = 1; i <= total; i++) {
    doc.setPage(i);
    drawFooter(i, total);
  }

  return doc.output("blob");
}

// Robust blob download — works without file-saver. Uses an anchor + object URL
// which is the same approach file-saver uses internally on modern browsers.
export async function downloadBlob(blob, filename) {
  if (typeof window === "undefined") return false;
  try {
    // Try file-saver first if it's installed (handles old IE / Safari quirks).
    try {
      const mod = await import("file-saver");
      const saveAs = mod.saveAs || (mod.default && mod.default.saveAs);
      if (typeof saveAs === "function") {
        saveAs(blob, filename);
        return true;
      }
    } catch {
      /* fall through to native */
    }
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    a.rel = "noopener";
    a.style.display = "none";
    document.body.appendChild(a);
    a.click();
    setTimeout(() => {
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }, 0);
    return true;
  } catch (e) {
    console.error("downloadBlob failed", e);
    return false;
  }
}

// Build a friendly file name like NDA_ABC_Pvt_Ltd_2026-05-15
export function buildFileName({ counterparty, prefix = "NDA", date }) {
  const safe = (s) =>
    String(s || "Document")
      .replace(/[^A-Za-z0-9]+/g, "_")
      .replace(/^_|_$/g, "")
      .slice(0, 60);
  const d = date ? new Date(date) : new Date();
  const iso = isNaN(d) ? new Date().toISOString().slice(0, 10) : d.toISOString().slice(0, 10);
  return `${prefix}_${safe(counterparty)}_${iso}`;
}

export function buildDocumentId(prefix = "DOC") {
  const t = Date.now().toString(36).toUpperCase().slice(-6);
  const r = Math.random().toString(36).toUpperCase().slice(2, 5);
  return `${prefix}-${t}${r}`;
}
